### ISSUE TITLE
Error when trying GPU

### ISSUE THREAD

**Issue by skaywolk3r** [deep-man-yy/easydeepnude#2]
![Ekran Alıntısı](https://user-images.githubusercontent.com/41342861/60772955-37d39680-a106-11e9-9500-383f33c4918e.PNG)

I tried different numbers but still same. I have 10.0 version that you give link at readme.

**Comment by deep-man-yy** [comment]
What a weird error, although it sounds like a corrupt installation of CUDA. Try re-installing CUDA or installing the latest drivers for your graphics card.

**Comment by skaywolk3r** [comment]
fixed when uninstall cuda
